name: Bindings

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  build-bindings:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { name: SDL, os: windows-2022, file: SDL.sh }
    
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: ClangSharp
        shell: bash
        run: |
          dotnet tool install --global ClangSharpPInvokeGenerator
          echo "$HOME/.dotnet/tools" >> "$GITHUB_PATH"

      - name: Build
        shell: bash
        env:
          NAME: ${{ matrix.name }}
          CPU: ${{ matrix.cpu }}
        run: |
          chmod +x .github/scripts/Bindings/${{ matrix.file }}
          ./.github/scripts/Bindings/${{ matrix.file }}

      - name: Upload
        uses: actions/upload-artifact@v7.0.1
        with:
          name: ${{ matrix.name }}
          path: outputs
  
  publish:
    name: Publish
    needs: build-bindings
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
        with:
          ref: ${{ github.ref_name }}
          persist-credentials: true
          fetch-depth: 0

      - name: Configure
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config --global url."https://x-access-token:${GH_TOKEN}@github.com/".insteadOf "https://github.com/"

      - name: Branch
        run: |
          git push origin --delete Bindings || true
          git checkout --orphan Bindings
          git rm -rf . || true
          git clean -fdx || true

      - name: Download
        uses: actions/download-artifact@v8.0.1
        with:
          path: artifacts
          skip-decompress: true

      - name: Commit
        run: |
          find artifacts -type f -name '*.zip' -print0 |
            while IFS= read -r -d '' zip; do
              name="$(basename "$zip" .zip)"
              mkdir -p "$name"
              unzip -q "$zip" -d "$name"
            done

          git add . ':!artifacts'
          git commit -m "Bindings"
          git push origin Bindings --force

      - name: Reference
        run: |
          SUBMODULE_PATH="Source/Natives/Bindings"
          
          git checkout ${{ github.ref_name }}
          
          if [ -d "$SUBMODULE_PATH/.git" ] || [ -f ".gitmodules" ]; then
            git submodule set-url "$SUBMODULE_PATH" "https://github.com/${{ github.repository }}"
          else
            git submodule add -f -b Bindings https://github.com/${{ github.repository }} $SUBMODULE_PATH || true
          fi
          
          git submodule set-branch -b Bindings -- "$SUBMODULE_PATH"
          git submodule update --init --force --remote "$SUBMODULE_PATH"
          
          git add .gitmodules "$SUBMODULE_PATH"
          git commit -m "Bindings" || echo "No changes"
          git push origin ${{ github.ref_name }}